# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20171118_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('photo_three', models.ImageField(upload_to='articles/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Editor')),
                ('tags', models.ManyToManyField(to='info.tags')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Photos_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('photo', models.ImageField(upload_to='articles/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Editor')),
                ('tags', models.ManyToManyField(to='info.tags')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photo_three',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photo_two',
        ),
    ]
