# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20171117_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('tag_image', models.ImageField(upload_to='articles/')),
            ],
        ),
    ]
