# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='articles/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Editor')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='photos',
            name='tags',
            field=models.ManyToManyField(to='info.tags'),
        ),
    ]
