# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20171119_0721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo_three',
            new_name='Photos_three',
        ),
    ]
